# FROM node:latest as build
# WORKDIR /app
# COPY package.json .
# RUN yarn install
# COPY . .
# RUN yarn run build
# FROM nginx
# COPY --from=build /app/build /usr/share/nginx/html

# Step 1: Build the React application
FROM node:16 as build

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the React app
RUN npm run build

# Step 2: Serve the React application with Nginx
FROM nginx:alpine

# Copy the built React app from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom Nginx configuration file if needed
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
